# Generated by Django 5.0.6 on 2024-12-01 20:20

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('App1Home', '0002_savedlisting_delete_useritems'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='UserItems',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('WantedItemName', models.CharField(max_length=200)),
                ('WantedItemPrice', models.IntegerField()),
                ('WantedItemLocation', models.CharField(max_length=200)),
                ('WantedItemURL', models.URLField()),
                ('WantedItemImage', models.URLField()),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.DeleteModel(
            name='SavedListing',
        ),
    ]
