# Generated by Django 5.0.6 on 2024-12-01 22:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('App1Home', '0003_useritems_delete_savedlisting'),
    ]

    operations = [
        migrations.AlterField(
            model_name='useritems',
            name='WantedItemPrice',
            field=models.DecimalField(decimal_places=2, max_digits=10),
        ),
    ]
