# Generated by Django 5.0.6 on 2024-12-02 01:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('App1Home', '0005_recentsearch'),
    ]

    operations = [
        migrations.CreateModel(
            name='PriceHistory',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('search_item', models.CharField(max_length=200)),
                ('avg_price', models.DecimalField(decimal_places=2, max_digits=10)),
                ('timestamp', models.DateTimeField(auto_now_add=True)),
            ],
        ),
    ]
